version: '3.8'

services:
  webserver:
    build:
      context: ../webserver/
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - client:/var/www/client
  client:
    entrypoint: bash
    command:
      - -c
      - |
        cp -a /src/client/output/* /var/www/client/
    build:
      context: ../client/
    volumes:
      - client:/var/www/client

volumes:
  client:

