version: '3.8'

services:
  webserver:
    build:
      context: ../webserver/
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - client:/var/www/client
  client:
    entrypoint: bash
    command:
      - -c
      - |
        cp -a /src/node_modules /src/client/
        cp -a /src/bower_components /src/client/
        ./afn-app.sh webdev
    build:
      context: ../client/
    volumes:
      - ../client/:/src/client/
      - client:/src/client/output/

volumes:
  client:

