name: Docker Image client

on:
  push:
    branches: ['**']
    paths: 
      - 'client/**'
      - '.github/workflows/docker-client.yml'
      - '!client/builder/**'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup VARS.js
        run: 'printf "$AFN_VARS" > client/assets/js/VARS.js'
        env:
          AFN_VARS : ${{secrets.AFN_VARS}}

      - name: Kaniko build full
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          image: client
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: cache
          path: client/
          extra_args: --push-retry 5
      
      - name: Kaniko build light
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          image: client-light
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: cache
          path: client/light/
          extra_args: --push-retry 5

