name: Docker Image client/base

on:
  push:
    branches: ['**']
    paths: 
      - 'client/base/**'
      - '.github/workflows/docker-client-base.yml'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-base
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/cache
          path: client/base/
          extra_args: --push-retry 5
