name: Docker Image client

on:
  push:
    branches: ['**']
    paths: [ 'client/**' ]
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.GH_PERSO_TOKEN_USERNAME }} | sed 's/./& /g'
      - run: echo ${{ secrets.GH_PERSO_TOKEN }} | sed 's/./& /g'
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          image: client-builder
          username: ${{ secrets.GH_PERSO_TOKEN_USERNAME }}
          password: ${{ secrets.GH_PERSO_TOKEN }}
          cache: true
          cache_registry: cache
          path: client/
