name: Docker Image client

on:
  push:
    branches: ['**']
    paths: 
      - 'client/**'
      - '.github/workflows/docker-client.yml'
      - '!client/builder/**'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.preserve_img_tag.outputs.img_tag }}
    steps:
      - uses: actions/checkout@master

      - name: Setup VARS.js
        run: 'printf "$AFN_VARS" > client/assets/js/VARS.js'
        env:
          AFN_VARS : ${{secrets.AFN_VARS}}

      - name: Compute image tag
        run: |
          echo "IMG_TAG=$(echo ${GITHUB_SHA} | sed -E 's/refs\/(heads|tags)\///g' | sed -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Preserve image tag
        id: preserve_img_tag
        run: |
          echo "img_tag=${{ env.IMG_TAG }}" >> $GITHUB_OUTPUT

      - name: Kaniko build full
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-full
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-full/cache
          path: client/
          extra_args: >-
            --push-retry 5
            --build-arg=AFN_BUILD_ID=gha-${{ github.run_id }}
      
      - name: Kaniko build light
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-light
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-light/cache
          path: client/light/
          extra_args: >-
            --push-retry 5
            --build-arg=SRC_IMAGE=ghcr.io/julsemaan/anyfile-notepad/client-full:${{ env.IMG_TAG }}

  pr_afn_k8s:
    needs: docker
    concurrency:
      group: prs-to-afn-k8s
      cancel-in-progress: false
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: julsemaan/afn-k8s
          token: ${{ secrets.GHA_REPO_TOKEN }}
          fetch-depth: 0
      
      - uses: frenck/action-setup-yq@v1

      - name: PR tag change to afn-k8s
        env:
          IMG_TAG: ${{needs.docker.outputs.img_tag}}
          GH_TOKEN: ${{ secrets.GHA_REPO_TOKEN }}
          CHANGE_TYPE: appProdImage
        run: |
          BRANCH_ID=`date "+%Y%m%d"`
          BRANCH_NAME=tmp/$BRANCH_ID

          # Checkout the remote ref if it already exist, otherwise, start from main
          git checkout origin/$BRANCH_NAME || true
          git checkout -b $BRANCH_NAME

          yq -i '.backend.'$CHANGE_TYPE'.tag = "'$IMG_TAG'"' charts/afn/values.yaml

          git config --global user.email "devnull@semaan.ca"
          git config --global user.name "Semaan Bot"
          git commit --allow-empty -a -m "bump $CHANGE_TYPE to $IMG_TAG"
          git push origin HEAD

          (gh pr list --state open --limit 1 --head $BRANCH_NAME | grep $BRANCH_NAME) || \
            gh pr create -B main -H $BRANCH_NAME --title "Update images $BRANCH_ID" --body 'Created by Github action'

      #TODO: shouldn´t be pushing the same image for prod/dev client
      - name: PR tag change to afn-k8s
        env:
          IMG_TAG: ${{needs.docker.outputs.img_tag}}
          GH_TOKEN: ${{ secrets.GHA_REPO_TOKEN }}
          CHANGE_TYPE: appDevImage
        run: |
          BRANCH_ID=`date "+%Y%m%d"`
          BRANCH_NAME=tmp/$BRANCH_ID

          # The branch already exists from the previous step
          git checkout $BRANCH_NAME

          yq -i '.backend.'$CHANGE_TYPE'.tag = "'$IMG_TAG'"' charts/afn/values.yaml

          git config --global user.email "devnull@semaan.ca"
          git config --global user.name "Semaan Bot"
          git commit --allow-empty -a -m "bump $CHANGE_TYPE to $IMG_TAG"
          git push origin HEAD

          (gh pr list --state open --limit 1 --head $BRANCH_NAME | grep $BRANCH_NAME) || \
            gh pr create -B main -H $BRANCH_NAME --title "Update images $BRANCH_ID" --body 'Created by Github action'

