name: Docker Image client/builder

on:
  push:
    branches: ['**']
    paths: [ 'client/builder/**' ]
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: client/builder/
          push: true
          tags: ghcr.io/julsemaan/anyfile-notepad/client-builder:latest
          cache-from: type=registry,ref=ghcr.io/julsemaan/anyfile-notepad/client-builder:buildcache
          cache-to: type=registry,ref=ghcr.io/julsemaan/anyfile-notepad/client-builder:buildcache,mode=max

