name: Docker Image client

on:
  push:
    branches: ['**']
    paths: 
      - 'client/**'
      - '.github/workflows/docker-client.yml'
      - '!client/builder/**'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup VARS.js
        run: 'printf "$AFN_VARS" > client/assets/js/VARS.js'
        env:
          AFN_VARS : ${{secrets.AFN_VARS}}

      - name: Compute image tag
        run: |
          echo "IMG_TAG=$(echo ${GITHUB_SHA} | sed -E 's/refs\/(heads|tags)\///g' | sed -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Kaniko build full
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-full
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-full/cache
          path: client/
          extra_args: >-
            --push-retry 5
            --build-arg=AFN_BUILD_ID=gha-${{ github.run_id }}
      
      - name: Kaniko build light
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-light
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-light/cache
          path: client/light/
          extra_args: >-
            --push-retry 5
            --build-arg=SRC_IMAGE=ghcr.io/julsemaan/anyfile-notepad/client-full:${{ env.IMG_TAG }}

