name: Docker Image client

on:
  push:
    branches: ['**']
    paths: 
      - 'client/**'
      - '.github/workflows/docker-client.yml'
      - '!client/builder/**'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup VARS.js
        run: 'printf "$AFN_VARS" > client/assets/js/VARS.js'
        env:
          AFN_VARS : ${{secrets.AFN_VARS}}

      - name: Kaniko build full
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-full
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-full/cache
          path: client/
          extra_args: --push-retry 5
      
      - name: Kaniko build light
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-light
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-light/cache
          path: client/light/
          extra_args: --push-retry 5

  deploy:
    needs: docker
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production-'
    runs-on: ubuntu-latest
    steps:

      - name: Use staging target servers if necessary
        run: |
          echo "TARGET_SERVERS=${{ secrets.ANSIBLE_STAGING_TARGET }} >> $GITHUB_ENV"
        if: github.ref == 'refs/heads/staging'

      - name: Use production target servers if necessary
        run: |
          echo "TARGET_SERVERS=${{ secrets.ANSIBLE_PRODUCTION_TARGET }} >> $GITHUB_ENV"
        if: github.ref == 'refs/heads/production'

      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AFN_MANAGER_HOST }}
          username: ${{ secrets.AFN_MANAGER_USERNAME }}
          key: ${{ secrets.AFN_MANAGER_KEY }}
          port: ${{ secrets.AFN_MANAGER_PORT }}
          script: |
            ${{ secrets.AFN_MANAGER_DEPLOY_CLIENT_SCRIPT }} ghcr.io/julsemaan/anyfile-notepad/client-light:${GITHUB_REF##*/} $TARGET_SERVERS

