name: Docker Image webserver

on:
  push:
    branches: ['**']
    paths: 
      - 'webserver/**'
      - '.github/workflows/docker-webserver.yml'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker-webserver:
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.preserve_img_tag.outputs.img_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        run: |
          echo "IMG_TAG=$(echo ${GITHUB_SHA} | sed -E 's/refs\/(heads|tags)\///g' | sed -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Preserve image tag
        id: preserve_img_tag
        run: |
          echo "img_tag=${{ env.IMG_TAG }}" >> $GITHUB_OUTPUT

      - name: Kaniko build
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/webserver
          tag: ${{ env.IMG_TAG }}
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/webserver/cache
          path: webserver/
          extra_args: --push-retry 5

  pr_afn_k8s:
    needs: docker-webserver
    concurrency:
      group: prs-to-afn-k8s
      cancel-in-progress: false
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: julsemaan/afn-k8s
          token: ${{ secrets.GHA_REPO_TOKEN }}
          fetch-depth: 0
      
      - uses: frenck/action-setup-yq@v1

      - name: PR tag change to afn-k8s
        env:
          IMG_TAG: ${{needs.docker-webserver.outputs.img_tag}}
          GH_TOKEN: ${{ secrets.GHA_REPO_TOKEN }}
        run: |
          BRANCH_ID=`date "+%Y%m%d"`
          BRANCH_NAME=tmp/$BRANCH_ID

          # Checkout the remote ref if it already exist, otherwise, start from main
          git checkout origin/$BRANCH_NAME || true
          git checkout -b $BRANCH_NAME

          yq -i '.backend.image.tag = "'$IMG_TAG'"' charts/afn/values.yaml

          git config --global user.email "devnull@semaan.ca"
          git config --global user.name "Semaan Bot"
          git commit --allow-empty -a -m "bump $CHANGE_TYPE to $IMG_TAG"
          git push origin HEAD

          (gh pr list --state open --limit 1 --head $BRANCH_NAME | grep $BRANCH_NAME) || \
            gh pr create -B main -H $BRANCH_NAME --title "Update images $BRANCH_ID" --body 'Created by Github action'

