name: Docker Image client

on:
  push:
    branches: ['**']
    paths: [ 'client/**' ]
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          image: client
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: cache
          path: client/builder/
          extra_args: --push-retry 5
