name: Docker Image client

on:
  push:
    branches: ['**']
    paths: [ 'client/**' ]
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: client/
          push: true
          tags: :latest
          cache-from: type=registry,ref=julsemaan/anyfile-notepad/client:buildcache
          cache-to: type=registry,ref=julsemaan/anyfile-notepad/client:buildcache,mode=max

