name: Docker Image client

on:
  push:
    branches: ['**']
    paths: 
      - 'client/**'
      - '.github/workflows/docker-client.yml'
      - '!client/builder/**'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup VARS.js
        run: 'printf "$AFN_VARS" > client/assets/js/VARS.js'
        env:
          AFN_VARS : ${{secrets.AFN_VARS}}

      - name: Compute image tag
        run: |
          echo "IMG_TAG=$(echo ${GITHUB_REF} | sed -E 's/refs\/(heads|tags)\///g' | sed -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Kaniko build full
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-full
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-full/cache
          path: client/
          extra_args: >-
            --push-retry 5
            --build-arg=AFN_BUILD_ID=gha-${{ github.run_id }}
      
      - name: Kaniko build light
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/client-light
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/client-light/cache
          path: client/light/
          extra_args: >-
            --push-retry 5
            --build-arg=SRC_IMAGE=ghcr.io/julsemaan/anyfile-notepad/client-full:${{ env.IMG_TAG }}

  deploy:
    needs: docker
    if: github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/production-'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use staging target servers if necessary
        run: |
          echo "TARGET_SERVERS=${{ secrets.ANSIBLE_STAGING_TARGET }}" >> $GITHUB_ENV
          echo "TARGET_IMAGE=staging" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/staging'

      - name: Use production target servers if necessary
        run: |
          echo "TARGET_SERVERS=${{ secrets.ANSIBLE_PRODUCTION_TARGET }}" >> $GITHUB_ENV
          echo "TARGET_IMAGE=production" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/production'

      - name: Setup deploy-env
        run: |
          echo "::set-output name=TARGET_SERVERS::$TARGET_SERVERS"
          echo "::set-output name=TARGET_IMAGE::$TARGET_IMAGE"
        id: deploy-env

      - name: Deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AFN_MANAGER_HOST }}
          username: ${{ secrets.AFN_MANAGER_USERNAME }}
          key: ${{ secrets.AFN_MANAGER_KEY }}
          port: ${{ secrets.AFN_MANAGER_PORT }}
          script: |
            ${{ secrets.AFN_MANAGER_DEPLOY_CLIENT_SCRIPT }} ghcr.io/julsemaan/anyfile-notepad/client-light:${{ steps.deploy-env.outputs.TARGET_IMAGE }} ${{ steps.deploy-env.outputs.TARGET_SERVERS }}

