name: Docker Image admin

on:
  push:
    branches: ['**']
    paths: 
      - 'admin/**'
      - '.github/workflows/docker-admin.yaml'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.preserve_img_tag.outputs.img_tag }}
    steps:
      - uses: actions/checkout@master

      - name: Setup VARS.js
        run: 'printf "$ADMIN_VARS" > admin/js/VARS.js'
        env:
          ADMIN_VARS: ${{secrets.ADMIN_VARS}}

      - name: Compute image tag
        run: |
          echo "IMG_TAG=$(echo ${GITHUB_SHA} | sed -E 's/refs\/(heads|tags)\///g' | sed -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Preserve image tag
        id: preserve_img_tag
        run: |
          echo "img_tag=${{ env.IMG_TAG }}" >> $GITHUB_OUTPUT

      - name: Kaniko build
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/admin
          tag: ${{ env.IMG_TAG }}
          tag_with_latest: false
          password: ${{ secrets.GITHUB_TOKEN }}
          path: admin/
          extra_args: >-
            --push-retry 5

  pr_afn_k8s:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          name: julsemaan/afn-k8s
      
      - name: Get IMG_TAG
        run: |
          echo $IMG_TAG
        env:
          IMG_TAG: ${{needs.docker.outputs.img_tag}}

      - name: Stage changes in new branch
        env:
          IMG_TAG: ${{needs.docker.outputs.img_tag}}
        run: |
          git checkout -b tmp/admin-$IMG_TAG
          git commit -a -m "bump admin to $IMG_TAG"
          git push origin HEAD
      
