name: Docker Image client/builder

on:
  push:
    paths: [ 'client/builder/**' ]
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: docker.pkg.github.com
          image: client-builder
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: cache
          path: client/builder/
=======
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make -C client/builder/ ghcr.io/julsemaan/anyfile-notepad/client/builder
>>>>>>> update docker client builder
