name: Docker Image webserver

on:
  push:
    branches: ['**']
    paths: 
      - 'webserver/**'
      - '.github/workflows/docker-webserver.yml'
  workflow_dispatch:
    branches: ['**']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Compute image tag
        run: |
          echo "IMG_TAG=$(echo ${GITHUB_SHA} | sed -E 's/refs\/(heads|tags)\///g' | sed -e 's/\//-/g')" >> $GITHUB_ENV

      - name: Kaniko build
        uses: julsemaan/action-kaniko@master
        with:
          registry: ghcr.io
          image: julsemaan/anyfile-notepad/webserver
          tag: ${{ env.IMG_TAG }}
          password: ${{ secrets.GITHUB_TOKEN }}
          cache: true
          cache_registry: ghcr.io/julsemaan/anyfile-notepad/webserver/cache
          path: webserver/
          extra_args: --push-retry 5

